### ISSUE TITLE
Secure npm username @riot

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/RIoT#5]
Will enable package names like `@riot/run` and `@riot/arduino-uno`

**Comment by artfuldev** [comment]
Sent email to existing holder tan_stream@mail.ru , awaiting response

**Comment by artfuldev** [comment]
How about `@r-iot/run` and `@r-iot/arduino-uno`?

**Comment by artfuldev** [comment]
We should probably think of new names, github.com/riot is also not available :(

**Comment by artfuldev** [comment]
Also talked to the core dev on the riot team via gitter. Awaiting response.

**Comment by ghost** [comment]
I suggest **I**React**To**/**I**React**oT** or something. What do you think?

**Comment by artfuldev** [comment]
Thanks for the suggestion, but I'm not quite satisfied. We're better off looking for something that is terse yet meaningful. Coming up with names is always a difficult task, and we'll have a lot of suggestion/feedback loops, please don't be disheartened. :)

**Comment by artfuldev** [comment]
UPDATE: riotjs devs contacted me saying they do not want 2 libraries with no semantic connection being around with the same name, so we have to think of new names

**Comment by artfuldev** [comment]
Continued in #6
