### ISSUE TITLE
Think of repository names

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/RIoT#6]
RIoT username/ repo / organization names are not available, due to an existing RIOT library https://github.com/riot/riot

So we need a meaningful, connectable, concise name.
All suggestions welcome, but we will wait to pick a name until we're satisfied.

We can vote on suggestions using **reactions**

**Comment by artfuldev** [comment]
Javascript of Things (JoT)
npm username `@jot` is available
github username `@jotjs` is available
js.org domain `jot.js.org` is available
twitter username `@jotjs` is **not** available

**Comment by artfuldev** [comment]
Reactive IoT Integrated Circuits (RIoTIC)
npm username `@riotic` is available
github username `@riotic` is available
js.org domain `riotic.js.org` is available
twitter username `@rioticjs` is available

**Comment by artfuldev** [comment]
Enabling Reactive Integrated Circuits Handily (EnRICH)
npm username `@enrich` is available
github username `@enrichjs` is available
js.org domain `enrich.js.org` is available
twitter username `@enrichjs` is available

**Comment by ghost** [comment]
Internet Of Reactions 
npm package `@ior` and `@internet-of-reactions` is available
github username `@ior` is **not** available but `@iorjs` and `@internet-of-reactions` is available
js.org domain `ior.js.org` and `internet-of-reactions.js.org` is available
twitter username `@ior` is **not** available but `@internet-of-reactions` is available.

**Comment by artfuldev** [comment]
Let's try to avoid hyphenation. ior and iorjs is good.

**Comment by artfuldev** [comment]
Reactive C Kit (ReaCKit) *reads like REAC..T*
npm package `@reackit` is available
github username `@reackit` is available
js.org domain `reackit.js.org` is available
twitter username `@reackit` is available

**Comment by artfuldev** [comment]
Amnis - Latin for current/flow/stream won it!
